name: Black Format Check

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - ".forgejo/workflows/black-format-check.yml"

  pull_request:
    branches: [ main ]
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - ".forgejo/workflows/black-format-check.yml"

jobs:
  black:
    runs-on: nixos
    steps:
    - uses: actions/checkout@v4
    - name: Check Code Formatting with Black
      run: |
        nix develop .#processintel --impure -c python -m black --check .