name: Run Unit Tests

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.py"
      - "tests/requirements_test.txt"
      - ".forgejo/workflows/unittest.yml"

  pull_request:
    branches: [ main ]
    paths:
      - "**/*.py"
      - "tests/requirements_test.txt"
      - ".forgejo/workflows/unittest.yml"

jobs:
  tests:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          nix develop .#processintel --impure --accept-flake-config -c python -m unittest discover -s tests -p "*_test.py"
